# Generated by Django 3.0.7 on 2021-02-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comments')),
            ],
        ),
    ]
